### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by harr1193** [harr1193/MI-449-SS17-741-html-multiple-pages-T_njfg#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://mi-449-ss17-741-html-multiple-pages-t_njfg-harr1193.surge.sh/) and meets the following criteria:

- [x] None of the routes on the website end with `.html`
- [x] A homepage exists, where the purpose of the site is explained
- [x] A "list page" exists that lists your top 3 favorite of this thing (e.g. `/pokemon`) -- each list item should link to the corresponding page for that favorite, detailed below
- [x] For each of your favorites, a page exists to display more information about it (e.g. `/pokemon/bulbasaur`) -- we want to make sure you practice multiple levels of nested routes
- [x] Every page includes links to the homepage and list page (although pages do not have to link to themselves)

**Comment by stuartpearman** [comment]
Hey Kyle, this is awesome! There's very little I'd do differently, but I would change one thing here.

You have duplicates for each game cover image in your nested pages. You can actually link to those original images the same way you link to your pages. So if your images are all in your root directory, you could link to them like this `/image.jpg`.

See if you can delete the duplicates and still get all the images working, let me know when you're done 👍

**Comment by harr1193** [comment]
Alright I got rid of the duplicates in the nested pages and moved them to the root directory

**Comment by stuartpearman** [comment]
Hey Kyle,

It looks like there are still duplicates of `mgs5.png`, `uc4.png`, and `last-of-us.png` in your root and favorites directories.

**Comment by harr1193** [comment]
The duplicates are removed from the favorites folder now

**Comment by stuartpearman** [comment]
Looks good! :shipit:
